#!/usr/bin/env bash

# setup
	YLW="\033[33;1m"
	GRN="\033[32;1m"
	WHT="\033[97;1m"
	BLU="\033[94;1m"
	RED="\033[91;1m"
	RES="\033[0m"

	if [[ $1 == "" ]]; then
		echo "No input given"
		echo "Usage: $0 input.txt"
		exit 1;
	fi

	input_file="$1"

	if [[ $input_file == 'example' ]]; then
		input_file="example.txt"
	fi

	# functions
		pause()
		{
			read -p "Press Enter to continue."
		}

		progressBar()
		{
			local input_file=$1
			local total=$(wc -l $input_file | grep -Eo '\d+' | head -1)
			local j

			echo -ne "Progress:\n["
			eval "printf -- ' %0.s' {1..$total}"
			echo -ne "]"

			if (( COLUMNS <= total )); then
				# echo "Big."
				# echo "Cols  $COLUMNS"
				# echo "Total $total"

				tput cuu 1 # move up 1 col
			fi
			echo -ne "\r["
		}
	# end functions
# setup


# prep
output_file='output.txt'
rm -f $output_file


# start here
lineNum=0
declare -A beams
declare -A nextBeams
splits=0
while IFS= read -u 11 -r line; do
	outLine="";
	
	for (( i=0; i<${#line}; i++ )); do
		char="${line:$i:1}"  # Extract one character at index 'i'

		case $char in
			'S') 
				# new beam starts here.
				nextBeams[$i]=Y
				outLine+="S";;

			'.') 
				# check if a beam should be here
				# echo "${beams[$i]}";

				if [[ ${beams[$i]} == "Y" ]]; then
					outLine+="|"
				else
					outLine+="."
				fi;;

			'^') 
				# split a beam from above (if there's a beam?)
				if [[ ${beams[$i]} == "Y" ]]; then
					nextBeams[$((i))]="N"
					nextBeams[$((i+1))]="Y"
					nextBeams[$((i-1))]="Y"
					((splits++))
				fi
				outLine+="^";;
		esac
	done

	# echo "$outLine" | tee -a $output_file
	echo "$outLine" >> $output_file

	beams=()
	for key in "${!nextBeams[@]}"; do
		beams["$key"]="${nextBeams[$key]}"
	done

	((lineNum++))
done 11< ${input_file}

cat $output_file
echo "Splits: $splits"




# --- Part Two ---



# --- Part One ---

# You thank the cephalopods for the help and exit the trash compactor, 
# finding yourself in the familiar halls of a North Pole research wing.

# Based on the large sign that says "teleporter hub", they seem to be researching teleportation; 
# you can't help but try it for yourself and step onto the large yellow teleporter pad.

# Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. 
# Unfortunately, the teleporter seems to be leaking magic smoke.

# Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. 
# After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

# You quickly locate a diagram of the tachyon manifold (your puzzle input). 
# A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. 
# Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), 
# the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

# For example:

# .......S.......
# ...............
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

# .......S.......
# .......|.......
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# At that point, the original beam stops, and two new beams are emitted from the splitter:

# .......S.......
# .......|.......
# ......|^|......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# Those beams continue downward until they reach more splitters:

# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............

# At this point, the two splitters create a total of only three tachyon beams, 
# since they are both dumping tachyons into the same place between them:

# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# .....|^|^|.....
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# This process continues until all of the tachyon beams reach a splitter or exit the manifold:

# .......S.......
# .......|.......
# ......|^|......
# ......|.|......
# .....|^|^|.....
# .....|.|.|.....
# ....|^|^|^|....
# ....|.|.|.|....
# ...|^|^|||^|...
# ...|.|.|||.|...
# ..|^|^|||^|^|..
# ..|.|.|||.|.|..
# .|^|||^||.||^|.
# .|.|||.||.||.|.
# |^|^|^|^|^|||^|
# |.|.|.|.|.|||.|
# To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. 
# In this example, a tachyon beam is split a total of 21 times.

# Analyze your manifold diagram. How many times will the beam be split?
